
vcenterip: 192.168.110.22
vcentercluster: RegionA01-K8s
vcenteruser: administrator@corp.local  
vcenterpassword: VMware1!
vcenterdc: RegionA01
vcentercluster: RegionA01-MGMT
PG_UPLINK: ESXi-RegionA01-vDS-COMP
PG_OVERLAY: VM-RegionA01-vDS-COMP
PG_UPLINK_VLANID: 756
