nsx_t_gen_params: &vsphere-config-params
  vcenterip: {{vcenterip}}
  vcenteruser: {{vcenteruser}}
  vcenterpassword: {{vcenterpassword}}
  vcenterdc: {{vcenterdc}}
  vcentercluster: {{vcentercluster}}
  PG_OVERLAY: {{PG_OVERLAY}}
  PG_UPLINK: {{PG_UPLINK}}
  PG_UPLINK_VLANID: {{PG_UPLINK_VLANID}}

resources:
- name: nsx-t-smoke-tests
  type: git
  source:
    uri: https://github.com/NiranEC77/nsx-t-smoke-tests
    branch: "master"

groups:
- name: all-tests
  jobs:
  - north-south
  - east-west
  - vsphere-config 
- name: vsphere-config
  jobs:
  - vsphere-config
- name: east-west
  jobs:
  - east-west
- name: north-south
  jobs:
  - north-south

jobs:
- name: vsphere-config
  plan:
  - aggregate:
    - get: nsx-t-smoke-tests
  - task: vsphere-config
    file: nsx-t-smoke-tests/tasks/vsphere-config/task.yml
    params: *vsphere-config-params

- name: east-west
  plan:
  - aggregate:
    - get: nsx-t-smoke-tests
      passed: [vsphere-config]
      trigger: true
  - task: east-west
    file: nsx-t-smoke-tests/tasks/east-west/task.yml

- name: north-south
  plan:
  - aggregate:
    - get: nsx-t-smoke-tests
      passed: [vsphere-config]
      trigger: true
  - task: north-south
    file: nsx-t-smoke-tests/tasks/north-south/task.yml

