---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-t-gen-worker}
inputs:
  - name: nsx-t-smoke-tests

run:
  path: nsx-t-smoke-tests/tasks/vsphere-config/task.sh

params:
  vcenterip:
  vcenteruser:
  vcenterpassword:
  vcenterdc:
  vcentercluster:
  PG_OVERLAY:
  PG_UPLINK:
  PG_UPLINK_VLANID:
